## 3. Creating Arrays with Specific Values

NumPy provides convenient functions to create arrays filled with specific values like **zeros**, **ones**, or **any custom value** you want. This is useful when you need to initialize arrays before performing calculations.

In [2]:
import numpy as np

### 3.1 Creating Arrays Filled with Zeros: `np.zeros()`

The `np.zeros()` function creates an array where all elements are **0**.

**Syntax**: `np.zeros(size)`

**Important**: The values are **float** by default (0.0, not integer 0). 

**Why float?** NumPy uses float as the default data type because:
- Most scientific and mathematical calculations require decimal precision
- Floating-point numbers can represent a wider range of values
- It's safer for numerical operations (avoids integer overflow)

In [3]:
array_zeros = np.zeros(10)
array_zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### 3.2 Creating Arrays Filled with Ones: `np.ones()`

The `np.ones()` function creates an array where all elements are **1**.

**Syntax**: `np.ones(size)`

**Important**: Just like `np.zeros()`, the values are **float** by default (1.0, not integer 1).

**Why float again?** Same reason:
- NumPy's default behavior for numerical consistency
- Prepared for mathematical operations that may need decimals
- You can convert to integers later if needed using `.astype(int)`

In [4]:
array_onses = np.ones(10)
array_onses

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### 3.3 Creating Identity Matrices: `np.eye()`

An **identity matrix** is a special square matrix (same number of rows and columns) where:
- All diagonal elements (top-left to bottom-right) are **1**
- All other elements are **0**

**Syntax**: `np.eye(n)` where `n` is the size (creates an n×n matrix)

**What it looks like**: For `np.eye(3)`:
```
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
```

**Important**: Like `np.zeros()` and `np.ones()`, values are **float** by default (1.0 and 0.0).

**Why is it useful?**
- In linear algebra, multiplying any matrix by the identity matrix gives you the original matrix
- It's like the number "1" in multiplication (5 × 1 = 5)
- Used in machine learning, computer graphics, and solving systems of equations

**Why float?** Same reason as before - NumPy's default for numerical precision in mathematical operations.

In [3]:
identity_matrix = np.eye(3) 
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 3.4 Creating Arrays with Custom Values: `np.full()`

The `np.full()` function creates an array where **all elements have the same custom value** that you specify.

**Syntax**: `np.full(size, fill_value=your_value)`

**Important difference from `np.zeros()`, `np.ones()`, and `np.eye()`**:
- `np.full()` uses the **data type of the value you provide**
- In our example, we use `int(input(...))`, so the value is an **integer**, not float
- This is why you see integer values like `[5 5 5 5 5 5 5 5 5 5]` instead of `[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]`

**Why NOT float?**
- We explicitly converted the input to integer using `int()`
- NumPy respects the data type you give it
- If you used `float(input(...))` instead, the array would contain float values

In [ ]:
specific_value = int(input("Enter the specific value to fill the array: ")) 
array_specific = np.full(10 , fill_value = specific_value) 
array_specific

array([6, 6, 6, 6, 6, 6, 6, 6, 6, 6])

### Key Differences Summary

| Function | Creates | Data Type | Why? |
|----------|---------|-----------|------|
| `np.zeros()` | All zeros | **Float** (0.0) | NumPy's default for numerical operations |
| `np.ones()` | All ones | **Float** (1.0) | NumPy's default for numerical operations |
| `np.eye()` | Identity matrix (1s on diagonal, 0s elsewhere) | **Float** (1.0 and 0.0) | NumPy's default for numerical operations |
| `np.full()` | All same custom value | **Depends on input** | Uses the type of value you provide |

**Remember**: 
- `np.zeros()`, `np.ones()`, and `np.eye()` → Always float by default
- `np.full()` → Uses the type you give it (int if you use `int()`, float if you use `float()`)

**When to use each?**
- `np.zeros()` → When you need an array of zeros (e.g., initializing counters)
- `np.ones()` → When you need an array of ones (e.g., creating masks or weights)
- `np.eye()` → When you need an identity matrix (e.g., linear algebra operations)
- `np.full()` → When you need an array filled with any specific value