## Working with ndarrays: Understanding Properties

Now that we know how to **create** arrays, let's learn how to **work with them** and understand their properties.

In this section, we'll explore the **`.shape` attribute**, which tells you the **dimensions** of your array (how many rows, columns, layers, etc.).

The `.shape` attribute is one of the most important properties you'll use when working with NumPy arrays!

In [2]:
import numpy as np 

### 1. Creating a 1D Array

Let's start by creating a simple 1D array with 10 elements using `np.arange(1, 11)`:
- This creates numbers from 1 to 10
- It's a single row of numbers (1-dimensional)

In [4]:
arr = np.arange(1 , 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### 2. Reshaping to a 2D Array

Now let's **reshape** this 1D array into a 2D array (table):
- `arr.reshape(2, 5)` converts the 10 elements into **2 rows × 5 columns**
- Think of it like arranging 10 numbers into a table with 2 rows and 5 columns

In [7]:
mat = arr.reshape(2, 5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

### 3. Creating a 3D Array

Finally, let's create a 3D array directly:
- `np.arange(1, 13).reshape(2, 2, 3)` creates 12 elements arranged in 3D
- **2 layers** × **2 rows** × **3 columns** (2×2×3 = 12 elements)
- Think of it like 2 stacked tables, each with 2 rows and 3 columns

In [10]:
ndarray = np.arange(1 , 13).reshape(2, 2, 3)
ndarray

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

---

## The `.shape` Attribute: Understanding Array Dimensions

The **`.shape`** attribute tells you the **size and dimensions** of an array. It returns a **tuple** (immutable list) with the size of each dimension.

**What it shows:**
- For a 1D array: `(n,)` → n elements in a single row
- For a 2D array: `(rows, columns)` → rows × columns table
- For a 3D array: `(layers, rows, columns)` → layers of tables
- For nD array: `(d1, d2, d3, ..., dn)` → size of each dimension

**How to use it:**
- `your_array.shape` returns a tuple with the shape
- You can unpack it: `rows, cols = arr.shape`
- It helps you verify your array has the expected structure

Let's see the shape of each array we created:

In [9]:
arr.shape

(10,)

**Shape of 1D array**: `(10,)` means 10 elements in a single row

In [8]:
mat.shape

(2, 5)

**Shape of 2D array**: `(2, 5)` means 2 rows × 5 columns (a 2×5 table)

In [11]:
ndarray.shape

(2, 2, 3)