# NumPy dtypes

Every NumPy array has a single data type (`dtype`). Knowing it helps you reason about speed, memory use, and how math behaves. In this walkthrough we:
- check what dtype an array has
- see how many bytes each element takes (`itemsize`)
- set dtypes up front
- cast safely when you need a different type

In [29]:
import numpy as np
print(np.__version__)

2.4.0


## Inspecting array dtypes
`arr.dtype` tells you the stored type (e.g., integers stay int, mixed numbers become float). Run the next cells and read the printed dtypes.

## Common NumPy `dtypes` at a glance

| dtype | What it represents | Typical bytes (`itemsize`) | Notes |
| --- | --- | --- | --- |
| bool | True/False | 1 | Masks, filters |
| int8 / uint8 | 8-bit integers (signed/unsigned) | 1 | uint8 common for images |
| int16 / uint16 | 16-bit integers (signed/unsigned) | 2 | Fits larger ranges |
| int32 / uint32 | 32-bit integers (signed/unsigned) | 4 | Default on many systems |
| int64 / uint64 | 64-bit integers (signed/unsigned) | 8 | Large ranges; more memory |
| float16 | Half precision float | 2 | Memory-light, less precision |
| float32 | Single precision float | 4 | Good speed/precision balance |
| float64 | Double precision float | 8 | Default floating type |
| complex64 | Two float32 parts | 8 | Real + imaginary |
| complex128 | Two float64 parts | 16 | Higher precision complex |
| datetime64 | Dates/times | 8 (unit-dependent) | Stores time with unit (ns, ms, etc.) |
| timedelta64 | Time differences | 8 (unit-dependent) | Durations with unit |
| object | Python objects | pointer-sized | Heterogeneous; slower |
| str_ / bytes_ | Fixed-length text/bytes | varies | Fixed-width; for variable text prefer Python objects |

Use `arr.dtype` to see which one you have. `itemsize` tells you how many bytes each element uses.

In [45]:
int_arr = np.array([1, 2, 3, 4, 5])
float_arr = np.array([1.0, 2.0, 3.0, 4.0, 5.0])
bool_arr = np.array([True, False, True])

In [46]:
print(int_arr.dtype)
print(float_arr.dtype)
print(bool_arr.dtype)

int64
float64
bool


## Specify `dtype` when creating arrays
Most NumPy constructors accept `dtype=`. Set it early to avoid surprises and extra conversions later.

In [38]:
fl_arr = np.arange(1, 10, dtype=float)
print(fl_arr)
print(fl_arr.dtype)
print(fl_arr.dtype.itemsize)

[1. 2. 3. 4. 5. 6. 7. 8. 9.]
float64
8


## What is `itemsize`?
- How many **bytes per element** this dtype needs (e.g., `float64` → 8 bytes, `float32` → 4 bytes, `uint8` → 1 byte).
- Total memory = `arr.size * arr.itemsize` (same as `arr.nbytes`).
- Useful for picking lighter dtypes when you don’t need full precision.

In [33]:
example_arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float32)
print(example_arr.dtype)
print(example_arr.itemsize)
print(example_arr.size)
print(example_arr.nbytes)
print(example_arr.size * example_arr.itemsize)

float32
4
6
24
24


## Casting with `astype()`
- `.astype(new_dtype)` returns a **new array**; the original stays the same.
- Float → int truncates toward zero, so choose the dtype you actually need.
- Be explicit: `np.int32`, `np.uint8`, `np.float64`, etc.

In [34]:
array_int = fl_arr.astype(np.int32)
array_float32 = array_int.astype(np.float32)
print(array_int)
print(array_int.dtype, array_int.dtype.itemsize)
print(array_float32)
print(array_float32.dtype, array_float32.dtype.itemsize)

[1 2 3 4 5 6 7 8 9]
int32 4
[1. 2. 3. 4. 5. 6. 7. 8. 9.]
float32 4


## Check cast safety before converting
`np.can_cast` tells you if a conversion loses information; `np.result_type` shows the dtype NumPy will pick when you mix types.

In [35]:
print(np.can_cast(np.float64, np.int32, casting="safe"))
print(np.can_cast(np.int32, np.float64, casting="safe"))
print(np.result_type(np.int32, np.float64))

False
True
float64


## Key takeaways
- Always check `.dtype` and `.itemsize` to know precision and memory cost.
- Set `dtype=` when creating arrays to avoid unwanted promotions.
- `astype` makes a copy; pick the target dtype intentionally.
- Use `np.can_cast` / `np.result_type` to see if a conversion is safe and what mixed math will produce.