## Working with ndarrays: Understanding Properties

Now that we can **create** arrays, let's learn to **inspect** them. Two key attributes give you quick insight:
- `.shape` → the exact size of each dimension
- `.ndim` → how many dimensions there are

We’ll build simple 1D, 2D, and 3D arrays, then read these attributes to understand their structure.

In [3]:
import numpy as np 

### 1. Creating a 1D Array

Let's start by creating a simple 1D array with 10 elements using `np.arange(1, 11)`:
- This creates numbers from 1 to 10
- It's a single row of numbers (1-dimensional)

In [14]:
arr = np.arange(1 , 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### 2. Reshaping to a 2D Array

Now let's **reshape** this 1D array into a 2D array (table):
- `arr.reshape(2, 5)` converts the 10 elements into **2 rows × 5 columns**
- Think of it like arranging 10 numbers into a table with 2 rows and 5 columns

In [5]:
mat = arr.reshape(2, 5)
mat

array([[ 1.4,  2.4,  3.4,  4.4,  5.4],
       [ 6.4,  7.4,  8.4,  9.4, 10.4]])

### 3. Creating a 3D Array

Finally, let's create a 3D array directly:
- `np.arange(1, 13).reshape(2, 2, 3)` creates 12 elements arranged in 3D
- **2 layers** × **2 rows** × **3 columns** (2×2×3 = 12 elements)
- Think of it like 2 stacked tables, each with 2 rows and 3 columns

In [6]:
ndarray = np.arange(1 , 13).reshape(2, 2, 3)
ndarray

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

---

## The `.shape` Attribute: Exact Size of Each Dimension

`.shape` returns a **tuple** with the length of every dimension, in order.

- 1D: `(n,)` → n elements in one dimension
- 2D: `(rows, cols)` → like a table
- 3D: `(layers, rows, cols)` → stacked tables
- nD: `(d1, d2, ..., dn)`

How to use:
- Call `array.shape` to see its layout
- Multiply the numbers in `.shape` to get total elements
- Unpack if helpful: `rows, cols = mat.shape`

Let's check the shapes of our arrays:

In [7]:
arr.shape

(10,)

**Shape of 1D array**: `(10,)` means 10 elements in a single row

In [8]:
mat.shape

(2, 5)

**Shape of 2D array**: `(2, 5)` means 2 rows × 5 columns (a 2×5 table)

In [9]:
ndarray.shape

(2, 2, 3)

---

## The `.ndim` Attribute: How Many Dimensions?

`.ndim` returns a single integer: the **count of dimensions**.
- `1` → 1D (a line of numbers)
- `2` → 2D (rows × cols table)
- `3` → 3D (layers of tables)
- `n` → nD (higher dimensions)

Difference from `.shape`:
- `.shape` → sizes of each dimension (tuple)
- `.ndim` → how many dimensions (number)

We'll read `.ndim` on each array below.

**1D Array `.ndim`**: Returns `1` because this array has **only 1 dimension** (it's a single list)

In [11]:
arr.ndim

1

**2D Array `.ndim`**: Returns `2` because this array has **2 dimensions** (rows and columns, like a table)

In [12]:
mat.ndim

2

**3D Array `.ndim`**: Returns `3` because this array has **3 dimensions** (layers, rows, and columns - like a cube)

In [13]:
ndarray.ndim

3

---

## Quick Recap

- Use `.shape` when you need the **exact sizes** of every dimension (returns a tuple)
- Use `.ndim` when you need the **count of dimensions** (returns a number)

These two attributes give you a fast sanity check before you reshape, slice, or compute.