# NumPy arithmetic on ndarrays

Quick, plain-English walkthrough of elementwise math in NumPy. We’ll create two simple arrays and apply common operations so you can see how each one behaves.

In [36]:
import numpy as np
print(np.__version__)

2.4.0


## Arrays we will use
Two same-length arrays so elementwise operations line up.

In [37]:
arr_1 = np.arange(10, 101, 10)
arr_2 = np.arange(5, 55, 5)
print(arr_1)
print(arr_2)

[ 10  20  30  40  50  60  70  80  90 100]
[ 5 10 15 20 25 30 35 40 45 50]


## Summary of operations
- Addition `+`
- Subtraction `-`
- Multiplication `*`
- Division `/`
- Floor division `//`
- Modulus `%`
- Power `**`

Each runs element by element because the arrays share the same shape.

In [38]:
add_arr = arr_1 + arr_2
print("Addition of two arrays:", add_arr)

Addition of two arrays: [ 15  30  45  60  75  90 105 120 135 150]


In [39]:
sub_arr = arr_1 - arr_2
print("Subtraction of two arrays:", sub_arr)

Subtraction of two arrays: [ 5 10 15 20 25 30 35 40 45 50]


In [40]:
mul_arr = arr_1 * arr_2
print("Multiplication of two arrays:", mul_arr)

Multiplication of two arrays: [  50  200  450  800 1250 1800 2450 3200 4050 5000]


In [41]:
try:
    div_arr = arr_1 / arr_2
    print("Division of two arrays:", div_arr)
except Exception as e:
    print("Division failed:", e)

Division of two arrays: [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]


In [42]:
floordiv_arr = arr_1 // arr_2
print("Floor division of two arrays:", floordiv_arr)

Floor division of two arrays: [2 2 2 2 2 2 2 2 2 2]


In [43]:
mod_arr = arr_1 % arr_2
print("Modulus of two arrays:", mod_arr)

Modulus of two arrays: [0 0 0 0 0 0 0 0 0 0]


In [44]:
pow_arr = arr_1 ** 2
print("Power of array 1 squared:", pow_arr)

Power of array 1 squared: [  100   400   900  1600  2500  3600  4900  6400  8100 10000]


## When shapes or sizes don't match
NumPy needs compatible shapes for broadcasting. The following quick demos show what happens when lengths or dimensions differ.

### Rules of Broadcasting (and why errors happen)
Broadcasting allows NumPy to work with arrays of different shapes, but they must follow strict rules. If they don't, you get a `ValueError`.

**The Rule:**
Compare the shapes starting from the **rightmost** dimension (end) and moving left. Two dimensions are compatible if:
1. They are **equal**, OR
2. One of them is **1** (which stretches to match the other).

If NumPy encounters a pair of dimensions that are neither equal nor 1, the operation fails.

**Common Failure Cases:**
*   **Length mismatch:** Trying to add `(3,)` and `(4,)` fails because 3 != 4.
*   **Dimension mismatch:** `(2, 2)` and `(2, 3, 2)` fails at the second-to-last dimension because 2 != 3 and neither is 1.

### 1D length mismatch
Trying to add arrays of length 3 and 5 raises a broadcast error.

In [ ]:
arr_short = np.arange(3)
arr_long = np.arange(5)
print("Shapes:", arr_short.shape, arr_long.shape)

try:
    print(arr_short + arr_long)
except ValueError as e:
    print("Error:", e)

Shapes: (3,) (5,)


Shapes: (3,) (5,)


ValueError: operands could not be broadcast together with shapes (3,) (5,) 

### Same rank, different width
A (1, 2) array cannot be added to a (1, 5) array.

In [ ]:
arr_2d = np.arange(2).reshape(1, 2)   # shape (1, 2)
arr_mismatch = np.arange(5).reshape(1, 5)  # shape (1, 5)
print("Shapes:", arr_2d.shape, arr_mismatch.shape)

try:
    print(arr_2d + arr_mismatch)
except ValueError as e:
    print("Error:", e)

Shapes: (1, 2) (1, 5)


Shapes: (1, 2) (1, 5)


ValueError: operands could not be broadcast together with shapes (1,2) (1,5) 

### Different dimensions (2D vs 3D)
A **(2, 2)** array cannot broadcast with a **(2, 3, 2)** array.
- Rightmost: 2 vs 2 (Match)
- Next: 2 vs 3 (Mismatch, and neither is 1) -> **Error**

### Different dimensions (1D vs 2D)
Here we try to add a 1D array of length **4** to a 2D array of shape **(2, 3)**.
- Rightmost match: 3 vs 4 needs to match. They are not equal, and neither is 1. -> **Error**.

In [ ]:
arr_1d_len4 = np.arange(4)            # shape (4,)
arr_2d_shape23 = np.zeros((2, 3))     # shape (2, 3)
print("Shapes:", arr_1d_len4.shape, arr_2d_shape23.shape)

try:
    print(arr_1d_len4 + arr_2d_shape23)
except ValueError as e:
    print("Error:", e)

Shapes: (3,) (2, 3)
[[0 2 4]
 [3 5 7]]


### Higher-rank mismatch (3D vs 4D)
A shape **(2, 2, 3)** vs **(2, 2, 2, 4)**.
- Rightmost comparison: 3 vs 4. Mismatch! -> **Error**.

In [ ]:
arr_3d = np.zeros((2, 2, 3))       # shape (2, 2, 3)
arr_4d = np.zeros((2, 2, 2, 4))    # shape (2, 2, 2, 4)
print("Shapes:", arr_3d.shape, arr_4d.shape)

try:
    print(arr_3d + arr_4d)
except ValueError as e:
    print("Error:", e)

Shapes: (2, 2, 3) (2, 2, 1, 3)
[[[[ 0  2  4]
   [ 3  5  7]]

  [[ 9 11 13]
   [12 14 16]]]


 [[[ 6  8 10]
   [ 9 11 13]]

  [[15 17 19]
   [18 20 22]]]]


In [ ]:
arr_2d = np.zeros((2, 2))       # shape (2, 2)
arr_3d = np.zeros((2, 3, 2))    # shape (2, 3, 2)
print("Shapes:", arr_2d.shape, arr_3d.shape)

try:
    print(arr_2d + arr_3d)
except ValueError as e:
    print("Error:", e)

Shapes: (2, 3) (2, 2, 3)
[[[ 0  2  4]
  [ 6  8 10]]

 [[ 6  8 10]
  [12 14 16]]]
