## Creating Multi-Dimensional Arrays (1D, 2D, 3D, and beyond)

NumPy allows you to create arrays with multiple dimensions:
- **1D Array**: A simple list (like a row of numbers)
- **2D Array**: A table with rows and columns (like a spreadsheet)
- **3D Array**: A cube of numbers (layers of tables)
- **nD Array**: Any number of dimensions!

Let's explore how to create each type.

In [3]:
import numpy as np 

### 1. Creating 1D Arrays

A **1D array** is like a single row of numbers - it's the simplest form.

**Method 1**: Use `np.array()` and pass a list of numbers in square brackets `[...]`
- `np.array([1,2,3,4,5,6,7,8,9])` → Creates a 1D array directly from a list

**Method 2**: Use `np.arange()` to generate a sequence
- `np.arange(10)` → Creates a 1D array with numbers from 0 to 9

Both methods create 1D arrays, just in different ways. Let's see them in action:

In [ ]:
oneD_array1 = np.array([1,2,3,4,5,6,7,8,9])
oneD_array2 = np.arange(10)
print(oneD_array1)
print(oneD_array2)

[1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


### 2. Creating 2D Arrays

A **2D array** is like a table with **rows and columns** - think of it as a spreadsheet or a chessboard.

**Method 1**: Use `np.array()` with nested lists (lists inside lists)
- `np.array([[1,2,3],[4,5,6],[7,8,9]])` → Creates a 3×3 table
- Each inner list `[...]` becomes a row

**Method 2**: Use `np.arange()` with `.reshape(rows, columns)`
- `np.arange(10).reshape(2,5)` → Takes numbers 0-9 and arranges them into 2 rows × 5 columns
- `.reshape()` is like cutting and pasting numbers into a specific shape

Let's see both methods:

In [7]:
twoD_array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(twoD_array1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
twoD_array2 = np.arange(10).reshape(2,5)
print(twoD_array2)

[[0 1 2 3 4]
 [5 6 7 8 9]]


### 3. Creating 3D Arrays

A **3D array** is like stacking multiple tables on top of each other - imagine a cube of numbers!

**Method 1**: Use `np.array()` with triple-nested lists
- `np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])` → Creates 2 layers, each with 2 rows × 3 columns
- Each outer list is a **layer**, each middle list is a **row**, each inner list contains the **values**

**Method 2**: Use `np.arange()` with `.reshape(layers, rows, columns)`
- `np.arange(1, 13).reshape(2, 2, 3)` → Takes 12 numbers and arranges them into 2 layers × 2 rows × 3 columns
- This is perfect for organizing 3D data!

Let's see both methods:

In [17]:
threeD_array1 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(threeD_array1)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [18]:
threeD_array2 = np.arange(1 , 13).reshape(2, 2, 3)
print(threeD_array2)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


### 4. Creating nD Arrays (4D, 5D, and beyond)

**Similarly**, we can create arrays with **any number of dimensions** using:
- `np.array()` with even more nested lists
- `.reshape()` with more dimensions specified

**Example**: 
- `np.arange(24).reshape(2, 3, 4, 1)` → Creates a 4D array
- `np.arange(120).reshape(2, 3, 4, 5)` → Creates a 4D array with 2×3×4×5 structure

The more dimensions you add, the more complex the organization becomes. Most real-world applications use 1D, 2D, or 3D arrays.

---

## Summary: Dimensions at a Glance

| Dimension | Shape | Looks Like | Example |
|-----------|-------|-----------|---------|
| **1D** | `(n,)` | A line of numbers | `[1, 2, 3, 4, 5]` |
| **2D** | `(rows, cols)` | A table/spreadsheet | `[[1,2],[3,4],[5,6]]` |
| **3D** | `(layers, rows, cols)` | Stacked tables/cube | `[[[1,2],[3,4]],[[5,6],[7,8]]]` |
| **nD** | `(d1, d2, ..., dn)` | Complex multi-layered structure | Limitless! |

**Two Ways to Create Arrays**:
1. **`np.array()`** → Directly specify the values with nested lists
2. **`np.arange().reshape()`** → Generate a sequence and reshape it into desired dimensions